Mvc
yurachel/web_app pull request #4
Opened 2021-05-29 14:39 UTC by yurachel

2021-06-07 20:33 UTC, artefactor requested changes

2021-06-07 20:33 UTC, artefactor commented on src/main/java/by/yurachel/web_app/dao/hibernate/impl/HibPhoneListDao.java
> +    public boolean update(String name, Phone object) {
ну соотвественно получился метод updateByName/
Но могут быть несколько телефонов с одинаковым именем. Это по идее не ошибка. лучше использовать id для этого.

Но у тебя name - это скорее natural_Id  т.е. Iphone 7 - два таких имени быть не может в интернет магазине.

2021-06-07 20:33 UTC, artefactor commented on src/main/java/by/yurachel/web_app/dao/jdbc/impl/JDBCPhoneListDAO.java
> +public class JDBCPhoneListDAO implements IDao<Phone> {
Обычно когда существуют такие аббревиатуры, то в java именованиях выглядит нечитаемо. получается
как JDBCP hone

поэтому часто пишут маленькими будквами для читаемости

JdbcPhone

так же с Dao вместо DAO - чтобы лучше читалось

2021-06-07 20:33 UTC, artefactor commented on src/main/java/by/yurachel/web_app/dao/jpa/impl/JPAPhoneListDAO.java
> +public class JPAPhoneListDAO implements IDao<Phone> {
название запутанное

JPAPhoneListDAO

объект у нас работает с телефонами а не листами, поэтому слово List - лишнее.

2021-06-07 20:33 UTC, artefactor commented on src/main/java/by/yurachel/web_app/entity/Phone.java
> +@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
а что он кэширует и как работает здесь кэш?

2021-06-07 20:33 UTC, artefactor commented on src/test/java/by/yurachel/web_app/controller/AddPhoneServletTest.java
>          addPhoneServlet.doPost(request, response);
тут обычно разделяют на секции
// given
//when
//then

2021-06-08 10:57 UTC, yurachel commented on src/main/java/by/yurachel/web_app/controller/UpdateServlet.java
>              Phone newPhone = new Phone(req.getParameter("name"),
Просто у меня реализация update такая,что не для этого у меня отдельная jsp,я захожу на нее,имя телефона служит в качестве ключа для поиска телефона в бд,и затем перезаписываются параметры этого телефона.

2021-06-19 14:27 UTC, merged